version: "3.8"


services:

  mongo:

    image: mongo:7.0.9

    container_name: mongo

    environment:

      MONGO_INITDB_ROOT_USERNAME: devdb

      MONGO_INITDB_ROOT_PASSWORD: dev@123


    ports:

      - "27017:27017"


    networks:

      - devops



  python-app:


    image: localhost:8082/docker-hosted/python-mongo-app:latest


    container_name: python-app


    environment:


      MONGO_DB_HOSTNAME: mongo

      MONGO_DB_USERNAME: devdb

      MONGO_DB_PASSWORD: dev@123


    ports:

      - "5000:5000"


    depends_on:

      - mongo


    networks:

      - devops



networks:

  devops:

    external: true